Repository apptension/saas-boilerplate, pull requests merged in 2023-06, with the labels that each got.

#199 fix: Squash user migrations and create initial superuser with UserProfile
  packages/backend/.coveragerc
  packages/backend/apps/users/migrations/0001_initial.py
  packages/backend/apps/users/migrations/0002_default_groups.py
  packages/backend/apps/users/migrations/0003_auto_20210716_1603.py
  packages/backend/apps/users/migrations/0004_user_otp_auth_url_user_otp_base32_user_otp_enabled_and_more.py
  packages/backend/apps/users/migrations/0005_alter_user_otp_auth_url_alter_user_otp_base32.py
  packages/backend/apps/users/migrations/0006_case_insensitive_collation.py
  packages/backend/apps/users/models.py
  packages/backend/sonar-project.properties
Labels: enhancement, python

#205 feat!: Load env variables required to build and deploy the app from AWS SSM Parameter Store instead of .env files
  .env.stage-example
  Makefile
  packages/infra/infra-shared/package.json
  packages/infra/infra-shared/src/main.ts
  packages/infra/infra-shared/src/stacks/bootstrap/index.ts
  packages/infra/infra-shared/src/stacks/bootstrap/stack.ts
  packages/infra/infra-shared/src/stacks/ci/ciBackend.ts
  packages/infra/infra-shared/src/stacks/ci/ciComponents.ts
  packages/infra/infra-shared/src/stacks/ci/ciDocs.ts
  packages/infra/infra-shared/src/stacks/ci/ciEntrypoint.ts
  packages/infra/infra-shared/src/stacks/ci/ciServerless.ts
  packages/infra/infra-shared/src/stacks/ci/ciUploadVersion.ts
  packages/infra/infra-shared/src/stacks/ci/ciWebApp.ts
  packages/infra/infra-shared/src/stacks/ci/e2eTests.ts
  packages/internal/core/custom-task-runner.js
  packages/internal/core/package.json
  packages/internal/core/stage-env-validator.js
  packages/internal/docs/docs/api-reference/env-files.mdx
  packages/internal/docs/docs/aws/deploy-to-aws/configure-aws-credentials.mdx
  packages/internal/docs/docs/aws/deploy-to-aws/configure-hosted-zone.mdx
  packages/internal/docs/docs/aws/deploy-to-aws/create-env-stage-in-repo.mdx
  packages/internal/docs/docs/aws/deploy-to-aws/create-runtime-env-vars.mdx
  packages/internal/docs/docs/aws/deploy-to-aws/deploy-infrastructure.mdx
  packages/internal/docs/docs/aws/deploy-to-aws/index.mdx
  packages/internal/docs/docs/aws/deploy-to-aws/run-deployment-commands.mdx
  packages/internal/docs/sidebars.js
  pnpm-lock.yaml
Labels: enhancement

#231 fix: Sync stripe's Product and Price before initialising subscriptions
  packages/backend/scripts/run_local.sh
Labels: bug, python

#232 fix: Remove unknown argument errors on notification button component,…
  packages/webapp-libs/webapp-notifications/sonar-project.properties
  packages/webapp-libs/webapp-notifications/src/notifications.component.tsx
  packages/webapp-libs/webapp-notifications/src/notificationsButton/index.ts
  packages/webapp-libs/webapp-notifications/src/notificationsButton/notificationsButton.component.tsx
  packages/webapp-libs/webapp-notifications/src/notificationsButton/notificationsButton.styles.ts
  packages/webapp-libs/webapp-notifications/src/notificationsList/notificationsList.component.tsx
  packages/webapp-libs/webapp-notifications/src/notificationsList/notificationsList.stories.tsx
Labels: bug

#253 fix: Reference tools' env variables via AWS Parameter Store
  packages/infra/infra-shared/src/stacks/ci/ciServerless.ts
  packages/infra/infra-shared/src/stacks/ci/e2eTests.ts
  packages/internal/docs/docs/api-reference/env-files.mdx
  packages/internal/docs/docs/aws/deploy-to-aws/create-env-stage-in-repo.mdx
  packages/internal/docs/docs/working-with-sb/dev-tools/version-matrix.mdx
  packages/internal/status-dashboard/package.json
  packages/internal/tools/project.json
Labels: bug
